version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: cargo
    directory: '/app/wasm/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cargo:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/app'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      nextjs:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/infra'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    cdk:
      nextjs:
        patterns:
          - '*'
