name: Build

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: 'ubuntu-latest'

    steps:
    - name: Update Rust toolchain
      run: rustup update
    - name: Install cross
      run: cargo install cross
    - uses: actions/checkout@v4
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        check-latest: true

    - name: Install pnpm    
      uses: pnpm/action-setup@v4
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]
        
    - name: Build (infra)
      working-directory: infra
      run: pnpm build

    - name: Build (app)
      working-directory: app
      run: pnpm lint && pnpm build
